// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: annotations.proto

package com.github.liuzhixing.domain.grpc;

/**
 * @ClassName AnnotationsProto
 * @Description protobuf类
 * @Author liuzhixing
 * @Date 2019-09-18 17:59
 **/
public final class AnnotationsProto {
  private AnnotationsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.github.liuzhixing.domain.grpc.AnnotationsProto.http);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int HTTP_FIELD_NUMBER = 72295728;
  /**
   * <pre>
   * See `HttpRule`.
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      com.github.liuzhixing.domain.grpc.HttpRule> http = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.github.liuzhixing.domain.grpc.HttpRule.class,
        com.github.liuzhixing.domain.grpc.HttpRule.getDefaultInstance());

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021annotations.proto\022\ngoogle.api\032\nhttp.pr" +
      "oto\032 google/protobuf/descriptor.proto:E\n" +
      "\004http\022\036.google.protobuf.MethodOptions\030\260\312" +
      "\274\" \001(\0132\024.google.api.HttpRuleB\201\001\n!com.huy" +
      "a.liuzhixing.domain.grpcB\020AnnotationsP" +
      "rotoP\001ZAgoogle.golang.org/genproto/googl" +
      "eapis/api/annotations;annotations\242\002\004GAPI" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.liuzhixing.domain.grpc.HttpProto.getDescriptor(),
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    http.internalInit(descriptor.getExtensions().get(0));
    com.github.liuzhixing.domain.grpc.HttpProto.getDescriptor();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
